#!/bin/bash
# set -euo pipefail
set -x
URL=${URL:-https://p.datadoghq.com/sb/42c2cc0b7-6c7d7a0eb5cb6a47078abf320b0aa847}

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

rm -rf /tmp/*

if [ -n "$REMOTE_HOST" ]; then
  cat <<EOF > /etc/openvpn.conf
client
nobind
remote-random
remote $REMOTE_HOST $REMOTE_PORT
proto tcp
mute 5
dev tun
<ca>
$( echo -e "$CERT" )
</ca>
auth-user-pass /etc/openvpn.credentials
EOF
  ( umask 0077; echo -e "${VPN_USER}\n${VPN_PASS}" > /etc/openvpn.credentials )
  openvpn --config /etc/openvpn.conf &
fi

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

dropbear -E -F &
DB_PID=$!

Xorg &
X_PID=$!

echo "Waiting for X to be ready"
export DISPLAY=:0

# Setting wallpaper and polling X in one!
while ! feh --bg-scale /etc/wallpaper.png; do sleep 1; done
matchbox-window-manager -use_cursor no &

while ! curl -sf -o /dev/null "$URL"; do sleep 1; done

xset -dpms
xset s off
xset s noblank

iceweasel "$URL"

sleep infinity
